### ISSUE TITLE
关于MatchPath和MatchItem的不懂之处

### ISSUE THREAD

**Issue by wqycsu** [Rogero0o/MatchView#1]
你好，请教两个问题：
1、MatchPath中的左右竖线以及上下横线为什么坐标要取负数呢，不太理解？
2、MatchItem的构造函数中，取中间点来计算又是为了什么呢？
忘解答，谢谢！

**Comment by Rogero0o** [comment]
1.左右竖线和上下横线是Button特有的，也是在有字母和数字之后才加的，所以设为负数，方便调整
2.中间点是为了计算偏移量用的，在MatchView的onDraw中使用

**Comment by liufsd** [comment]
如果支持中文就好了的。

**Comment by wqycsu** [comment]
每一个字体都是在onDraw中画出来的，中文汉字太多了，不像英文和数字可以通过定义一个简单字典集来定义。
