### ISSUE TITLE
Issue about MatchTextView

### ISSUE THREAD

**Issue by GauravCreed** [Rogero0o/MatchView#2]
Hi.
I am using your library, your code is superb,
1).         i have a issue for the set a Long text in that MatchTextView
2).         MatchTextView Can not Support Special Character Like ( Dotts, Semicolans,commas,etc.)
3).         MatchTextView Also not Support WrapContent like MSWord or Notepad

Please help me to sort-out this issue.
Thanks.

**Comment by Rogero0o** [comment]
Thank you for your issue.
I'm sorry to tell you that MatchTextView is designed for some short text only with letter ..
It will be stuttering if the text  too long , and it's too complicated to support Special Character.

**Comment by GauravCreed** [comment]
Thanks for the response.

can i Bold this text.?

**Comment by Rogero0o** [comment]
Yes . Of course
