### ISSUE TITLE
Add EditText

### ISSUE THREAD

**Issue by tellfa** [Rogero0o/MatchView#4]
Hi, thank you for this library! 
please add EditText with this effect

**Comment by Rogero0o** [comment]
Sorry , I don't think EditText is suitable for this effect .

**Comment by tellfa** [comment]
i need this :cry:

**Comment by Rogero0o** [comment]
I don't understand , What it will looks like an EditText with this effect ? 
Do you mean the word flying to the position?

**Comment by tellfa** [comment]
This library (MatchView) you develop TextView and Button. please develop too EditText such as this effect (MatchView)

https://camo.githubusercontent.com/a71e9d26a7f90ea70270b3681d99785a29f83be5/687474703a2f2f7777312e73696e61696d672e636e2f6d773639302f6136393561636465677731656d79746e6b347334356732306567306d6b3439302e676966

**Comment by Rogero0o** [comment]
You mean after input letters into the EditText ? OK

**Comment by tellfa** [comment]
thank you very much my dear friend :heart:

**Comment by tyhjh** [comment]
I am Chinese,when i use Chinese procedure crumble

**Comment by Rogero0o** [comment]
Sorry , It only support English letters .
