### ISSUE TITLE
Not supported RTL language

### ISSUE THREAD

**Issue by tellfa** [Rogero0o/MatchView#5]
Hi again, this library not supported RTL language. please fix this bug
when set RTL language to match:text="تست" , show Force Close error !

**Comment by Rogero0o** [comment]
I'm sorry to tell you that it's only support English letters .

**Comment by tellfa** [comment]
can you added RTL letters ? please

**Comment by Rogero0o** [comment]
Sorry~ The RTL language is too difficult and it's impossible to be done , if you have read the code you will know that .
