### ISSUE TITLE
Just a question. How did you manage to change the typeface of the text? 

### ISSUE THREAD

**Issue by DalveerSinghDaiya** [Rogero0o/MatchView#6]

**Comment by Rogero0o** [comment]
Sorry for answer you so late .
The code that change the typeface of the text is in the MatchView.java method onDraw() .
367 - 383 row.
Use Matrix to do it . Hope you can check the code. Thanks.

**Comment by DalveerSinghDaiya** [comment]
Thanks I found it. :)

*Dalveer Singh Daiya*
*Add Worth Rise Technologies*
Website : https://www.awrtechnologies.com
Email : <.dalveer@awrtechnologies.com <https://www.awrtechnologies.com/>>
